Repository akshay5995/powerbi-report-component, pull requests merged in 2020-05, with the labels that each got.

#210 Fix breaking issue of mulitple pages of same report in same web page
  src/lib/Embed.jsx
  src/lib/common/utils.js
Labels: bug-fix

#212 Refactor UI for Docs
  docs/bundle.js
  docs/index.html
  package-lock.json
  package.json
  src/docs/App.jsx
  src/docs/CreateReport/Form.jsx
  src/docs/CreateReport/index.jsx
  src/docs/Dashboard/Form.jsx
  src/docs/Dashboard/index.jsx
  src/docs/Report/Form.jsx
  src/docs/Report/index.jsx
  src/docs/Tile/Form.jsx
  src/docs/Tile/index.jsx
  src/docs/common/Footer.jsx
  src/docs/common/Header.jsx
  src/docs/common/SideNav.jsx
  src/docs/hooks/useLocalStorage.jsx
  src/docs/index.css
  src/docs/index.html
  src/docs/index.jsx
  src/docs/styles.css
  src/docs/utils.js
Labels: Code clean up

#218 Feature: useReport hook
  README.md
  src/docs/CreateReport/Form.jsx
  src/docs/Dashboard/Form.jsx
  src/docs/Dashboard/index.jsx
  src/docs/MultiplePageDemo/Form.jsx
  src/docs/Report/Form.jsx
  src/docs/Report/index.jsx
  src/docs/Tile/Form.jsx
  src/docs/common/formLayoutStyles.js
  src/lib/Dashboard/index.jsx
  src/lib/Embed.jsx
  src/lib/Report/index.jsx
  src/lib/Tile/index.jsx
  src/lib/common/Embed.jsx
  src/lib/common/onEmbedHandlers.js
  src/lib/hooks/useReport.js
  src/lib/index.jsx
  src/lib/utils/config.js
  src/lib/utils/constants.js
  src/lib/utils/index.js
Labels: bug-fix, enhancement

#241 Add typescript support
  package-lock.json
  package.json
  src/docs/CreateReport/index.jsx
  src/docs/Dashboard/index.jsx
  src/docs/MultiplePageDemo/index.jsx
  src/docs/Report/index.jsx
  src/docs/Tile/index.jsx
  src/docs/UseReportDemo/index.jsx
  src/docs/index.css
  src/lib/Dashboard.tsx
  src/lib/Dashboard/index.jsx
  src/lib/Embed.tsx
  src/lib/Report.tsx
  src/lib/Report/index.jsx
  src/lib/Tile.tsx
  src/lib/Tile/index.jsx
  src/lib/common/Embed.jsx
  src/lib/hooks/useReport.ts
  src/lib/index.tsx
  src/lib/types.ts
  src/lib/utils/config.js
  src/lib/utils/config.ts
  src/lib/utils/constants.js
  src/lib/utils/index.js
  src/lib/utils/index.ts
  src/lib/utils/onEmbedHandlers.ts
  tsconfig.json
Labels: enhancement, minor
