Repository akshay5995/powerbi-report-component, pull requests merged in 2020-04, with the labels that each got.

#169 [Feature] Enable create report mode
  src/docs/index.jsx
  src/docs/styles.css
  src/docs/utils.js
  src/lib/Embed.jsx
  src/lib/index.jsx
  src/lib/utils.js
Labels: minor

#176 Add embed-id to rendering div to solve multiple embed issue
  src/lib/Embed.jsx
Labels: bug-fix

#177 Reafactor and add tile mode
  src/docs/index.jsx
  src/docs/utils.js
  src/lib/Embed.jsx
  src/lib/config.js
  src/lib/index.jsx
  src/lib/onEmbedHandlers.js
  src/lib/utils.js
Labels: enhancement

#199 [Refactor] Export different types of embed objects instead of generic Report
  .babelrc
  README.md
  package-lock.json
  package.json
  src/docs/index.jsx
  src/docs/utils.js
  src/lib/Dashboard/index.jsx
  src/lib/Embed.jsx
  src/lib/Report/index.jsx
  src/lib/Tile/index.jsx
  src/lib/common/config.js
  src/lib/common/constants.js
  src/lib/common/onEmbedHandlers.js
  src/lib/common/utils.js
  src/lib/config.js
  src/lib/index.jsx
  webpack.config.js
Labels: major, refactor
